### ISSUE TITLE
cannot compile `nfpcapd` in 1.7.3

### ISSUE THREAD

**Issue by philhagen** [phaag/nfdump#480]
using the same `./configure` statement, compilation works fine with 1.7.2, but in 1.7.3, the following is reported:
```
checking pcap.h usability... no
checking pcap.h presence... yes
configure: WARNING: pcap.h: present but cannot be compiled
configure: WARNING: pcap.h:     check for missing prerequisite headers?
configure: WARNING: pcap.h: see the Autoconf documentation
configure: WARNING: pcap.h:     section "Present But Cannot Be Compiled"
configure: WARNING: pcap.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------- ##
configure: WARNING:     ## Report this to peter@people.ops-trust.net ##
configure: WARNING:     ## ----------------------------------------- ##
checking for pcap.h... no
configure: error: Required pcap.h header file not found!
```

this is on a CentOS 7 system with libpcap-devel 1.5.3.

I've attached [config.log](https://github.com/phaag/nfdump/files/13205783/config.log) from the failed `./configure`, but the problem is a lot of errors such as the following:

```
/usr/include/pcap/bpf.h:91:1: error: unknown type name 'u_int'
 typedef u_int bpf_u_int32;
 ^
```

If I omit `--enable-nfpcapd`, `./configure` exits cleanly.

**Comment by phaag** [comment]
Hmm .. CentOS headers seem not to be compatible with c99, which is the fallback.

**Comment by phaag** [comment]
It is fixed in latest master repo.
